image: node:lts

pages:
  stage: build
  script:
    - npm ci
    - npm run build
    - mv dist public

  artifacts:
    paths:
      - public

  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: on_success
